

spring.datasource.url=jdbc:postgresql://motoscan-postgres-server.postgres.database.azure.com:5432/motoscandb?sslmode=require
spring.datasource.username=sqladmin@motoscan-postgres-server
spring.datasource.password=SuaSenha123!
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuração do JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate 

# Configuração do Flyway
spring.flyway.enabled=true
# Define o perfil "dev" (desenvolvimento) como o padrão.
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.profiles.active=dev
